### ISSUE TITLE
In vendor_lighthouse/tools/custom-apns.py, path error on line 24

### ISSUE THREAD

**Issue by iprouteth0** [lighthouse-os/vendor_lighthouse#1]
Line 24 is 

original_file = 'vendor/lineage/prebuilt/common/etc/apns-conf.xml'

And should be

original_file = 'vendor/lighthouse/prebuilt/common/etc/apns-conf.xml'

I'm still learning git and have not yet learned to submit changes or commits.

**Comment by galanteria01** [comment]
@iprouteth0 Owo

**Comment by CannedShroud** [comment]
Fixed, Thanks for the response.
